/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface KeygenParams {
  roomId: string
  participantIndex: number
  participantsCount: number
  participantsThreshold: number
  relayAddress: string
  timeoutSeconds: number
}
export interface KeygenResult {
  key?: string
  error?: string
}
export interface SignParams {
  roomId: string
  key: string
  data: string
  participantsIndexes: Array<number>
  relayAddress: string
  timeoutSeconds: number
}
export interface SignResult {
  result?: string
  error?: string
}
/**
 *
 * Re-Exports
 *
 */
export function getVersion(): string
export function keygen(params: KeygenParams): Promise<KeygenResult>
export function sign(params: SignParams): Promise<SignResult>
/**
 *
 * Ethers
 *
 */
export interface EthersResult {
  result?: string
  error?: string
}
export function publicKeyToEthereumAddress(publicKey: string): EthersResult
export function privateKeyToEthereumAddress(privateKey: string): EthersResult
export function privateKeyToPublicKey(privateKey: string, compressed?: boolean | undefined | null): EthersResult
export function encodeMessageSignature(messageHash: string, chainId: number, signatureRecid: string): EthersResult
